### ISSUE TITLE
Settings -> Debug tools -> Get Node logs does not work in Wails (Desktop) mode 

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#265]
```
API Response: {"stack":"Error: Invalid log type: 'node?maxLen=1200'\n    at request (http://wails.localhost/assets/index-3cb78260.js:81:13919)\n    at async xa (http://wails.localhost/assets/index-3cb78260.js:5431:1888)","message":"Invalid log type: 'node?maxLen=1200'"}
```

**Comment by rolznz** [comment]
@im-adithya can you try this specifically to ensure it works on mac?
