### ISSUE TITLE
Panic in go-nostr Relay code causes Alby Hub to ungracefully exit

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#824]
```
/go/pkg/mod/github.com/nbd-wtf/go-nostr@v0.35.0/relay.go:176 +0x206
created by github.com/nbd-wtf/go-nostr.(*Relay).ConnectWithTLS in goroutine 18918
/go/pkg/mod/github.com/nbd-wtf/go-nostr@v0.35.0/relay.go:180 +0xfd
github.com/nbd-wtf/go-nostr.(*Relay).ConnectWithTLS.func2()
goroutine 31429 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xacb05d]
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by rolznz** [comment]
We need to catch panics in`start.go` by moving the relay connection request into a method with recovery (see `closeRelay` as an example in the same file.)
```
relay, err = nostr.RelayConnect(ctx, relayUrl, nostr.WithNoticeHandler(svc.noticeHandler))
```
